http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    api-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNoSniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"
        customResponseHeaders:
          Content-Security-Policy: >
            default-src 'none';
            connect-src 'self';
            img-src 'none';
            script-src 'none';
            style-src 'none';
            object-src 'none';
            base-uri 'none';
            frame-ancestors 'none';

    www-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNoSniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"
        customResponseHeaders:
          Content-Security-Policy: >
            default-src 'self';
            script-src 'self';
            style-src 'self';
            img-src 'self' data:;
            font-src 'self';
            connect-src 'self' https://api.${DOMAIN};
            object-src 'none';
            base-uri 'self';
            frame-ancestors 'none';
            upgrade-insecure-requests;