version: "3.9"
networks: { web: { } }
services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports: [ "80:80","443:443" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik-dynamic:/etc/traefik/dynamic:ro
    networks: [ web ]

  api-blue:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-api:${API_BLUE_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.api-blue.loadbalancer.server.port=8080" ]
    networks: [ web ]
  api-green:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-api:${API_GREEN_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.api-green.loadbalancer.server.port=8080" ]
    networks: [ web ]

  justice-blue:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-justice:${JUSTICE_BLUE_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.justice-blue.loadbalancer.server.port=8080" ]
    networks: [ web ]
  justice-green:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-justice:${JUSTICE_GREEN_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.justice-green.loadbalancer.server.port=8080" ]
    networks: [ web ]

  finance-blue:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-finance:${FINANCE_BLUE_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.finance-blue.loadbalancer.server.port=8080" ]
    networks: [ web ]
  finance-green:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-finance:${FINANCE_GREEN_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.finance-green.loadbalancer.server.port=8080" ]
    networks: [ web ]

  education-blue:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-education:${EDU_BLUE_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.education-blue.loadbalancer.server.port=8080" ]
    networks: [ web ]
  education-green:
    image: ghcr.io/${GHCR_OWNER}/tsumiyoku-education:${EDU_GREEN_TAG}
    env_file: [ ".env" ]
    labels: [ "traefik.enable=true", "traefik.http.services.education-green.loadbalancer.server.port=8080" ]
    networks: [ web ]